from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,blank=True,null=True)
    name=models.CharField(max_length=200,null=True,blank=True)
    designation=models.CharField(max_length=200,null=True,blank=True)
    department =models.CharField(max_length=200,null=True,blank=True)
    doj =models.CharField(max_length=200,null=True,blank=True)          #date of joining
    email =models.CharField(max_length=200,null=True,blank=True)
    spint = models.CharField(max_length=200,null=True,blank=True)     #specialization in teaching
    spinre =models.CharField(max_length=200,null=True,blank=True)       #specialization in research
    reint =models.CharField(max_length=200,null=True,blank=True)        #research interest
    oe = models.TextField(null=True,blank=True)        #other work experience
    ae = models.TextField(null=True,blank=True)        #Administrative and academic positions
    app = models.TextField(null=True,blank=True)       #articles and paper published
    csw = models.TextField(null=True,blank=True)       #conferences,seminars and workshop
    oa = models.TextField(null=True,blank=True)        #other activities

    def __str__(self):
        return str(self.user)

class Education(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    d1=models.CharField(max_length=200,default=0)                       #degree
    s1=models.CharField(max_length=200,default=0)                       #subject
    c1 =models.CharField(max_length=200,default=0)                      #college
    y1 =models.CharField(max_length=200,default=0)                      #year
    d2 =models.CharField(max_length=200,default=0)
    s2 =models.CharField(max_length=200,default=0)
    c2 =models.CharField(max_length=200,default=0)
    y2 =models.CharField(max_length=200,default=0)
    d3 =models.CharField(max_length=200,default=0)
    s3 =models.CharField(max_length=200,default=0)
    c3 =models.CharField(max_length=200,default=0)
    y3 =models.CharField(max_length=200,default=0)
    d4 =models.CharField(max_length=200,default=0)
    s4 =models.CharField(max_length=200,default=0)
    c4 =models.CharField(max_length=200,default=0)
    y4 =models.CharField(max_length=200,default=0)
    d5 =models.CharField(max_length=200,default=0)
    s5 =models.CharField(max_length=200,default=0)
    c5 =models.CharField(max_length=200,default=0)
    y5 =models.CharField(max_length=200,default=0)
    d6 =models.CharField(max_length=200,default=0)
    s6 =models.CharField(max_length=200,default=0)
    c6 =models.CharField(max_length=200,default=0)
    y6 =models.CharField(max_length=200,default=0)
    d7 =models.CharField(max_length=200,default=0)
    s7 =models.CharField(max_length=200,default=0)
    c7 =models.CharField(max_length=200,default=0)
    y7 =models.CharField(max_length=200,default=0)
    d8 =models.CharField(max_length=200,default=0)
    s8 =models.CharField(max_length=200,default=0)
    c8 =models.CharField(max_length=200,default=0)
    y8 =models.CharField(max_length=200,default=0)

    def __str__(self):
        return str(self.user)

class oe(models.Model):                                                                 #other work experiences
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    d1 = models.CharField(max_length=200, default=0)                                    #designation
    i1 = models.CharField(max_length=200, default=0)                                    #institution
    y1 = models.CharField(max_length=200, default=0)                                    #year
    d2 = models.CharField(max_length=200, default=0)
    i2 = models.CharField(max_length=200, default=0)
    y2 = models.CharField(max_length=200, default=0)
    d3 = models.CharField(max_length=200, default=0)
    i3 = models.CharField(max_length=200, default=0)
    y3 = models.CharField(max_length=200, default=0)
    d4 = models.CharField(max_length=200, default=0)
    i4 = models.CharField(max_length=200, default=0)
    y4 = models.CharField(max_length=200, default=0)
    d5 = models.CharField(max_length=200, default=0)
    i5 = models.CharField(max_length=200, default=0)
    y5 = models.CharField(max_length=200, default=0)

    def __str__(self):
        return str(self.user)

class ap(models.Model):                                                                 #Administrative /Academic Position/s (held/currently holding):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    ph1=models.CharField(max_length=200, default=0)                                     #position
    y1=models.CharField(max_length=200, default=0)                                      #year
    ph2 = models.CharField(max_length=200, default=0)
    y2 = models.CharField(max_length=200, default=0)
    ph3 = models.CharField(max_length=200, default=0)
    y3 = models.CharField(max_length=200, default=0)
    ph4 = models.CharField(max_length=200, default=0)
    y4 = models.CharField(max_length=200, default=0)
    ph5 = models.CharField(max_length=200, default=0)
    y5= models.CharField(max_length=200, default=0)
    ph6 = models.CharField(max_length=200, default=0)
    y6= models.CharField(max_length=200, default=0)
    ph7 = models.CharField(max_length=200, default=0)
    y7= models.CharField(max_length=200, default=0)
    ph8 = models.CharField(max_length=200, default=0)
    y8 = models.CharField(max_length=200, default=0)
    ph9 = models.CharField(max_length=200, default=0)
    y9= models.CharField(max_length=200, default=0)
    ph10 = models.CharField(max_length=200, default=0)
    y10 = models.CharField(max_length=200, default=0)
    ph11 = models.CharField(max_length=200, default=0)
    y11 = models.CharField(max_length=200, default=0)
    ph12 = models.CharField(max_length=200, default=0)
    y12 = models.CharField(max_length=200, default=0)
    ph13 = models.CharField(max_length=200, default=0)
    y13 = models.CharField(max_length=200, default=0)
    ph14 = models.CharField(max_length=200, default=0)
    y14= models.CharField(max_length=200, default=0)
    ph15 = models.CharField(max_length=200, default=0)
    y15= models.CharField(max_length=200, default=0)
    ph16 = models.CharField(max_length=200, default=0)
    y16= models.CharField(max_length=200, default=0)
    ph17 = models.CharField(max_length=200, default=0)
    y17= models.CharField(max_length=200, default=0)
    ph18 = models.CharField(max_length=200, default=0)
    y18= models.CharField(max_length=200, default=0)
    ph19 = models.CharField(max_length=200, default=0)
    y19 = models.CharField(max_length=200, default=0)
    ph20 = models.CharField(max_length=200, default=0)
    y20= models.CharField(max_length=200, default=0)
    ph21 = models.CharField(max_length=200, default=0)
    y21= models.CharField(max_length=200, default=0)
    ph22 = models.CharField(max_length=200, default=0)
    y22= models.CharField(max_length=200, default=0)
    ph23 = models.CharField(max_length=200, default=0)
    y23= models.CharField(max_length=200, default=0)
    ph24 = models.CharField(max_length=200, default=0)
    y24 = models.CharField(max_length=200, default=0)
    ph25 = models.CharField(max_length=200, default=0)
    y25 = models.CharField(max_length=200, default=0)

    def __str__(self):
        return str(self.user)

class article(models.Model):                                                    #Articles Published
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    t1=models.CharField(max_length=200, default=0)                               #title
    y1=models.CharField(max_length=200, default=0)                               #year
    j1=models.CharField(max_length=200, default=0)                               #journal
    n1=models.CharField(max_length=200, default=0)                               #international/national
    t2 = models.CharField(max_length=200, default=0)
    y2 = models.CharField(max_length=200, default=0)
    j2 = models.CharField(max_length=200, default=0)
    n2 = models.CharField(max_length=200, default=0)
    t3 = models.CharField(max_length=200, default=0)
    y3 = models.CharField(max_length=200, default=0)
    j3 = models.CharField(max_length=200, default=0)
    n3 = models.CharField(max_length=200, default=0)
    t4 = models.CharField(max_length=200, default=0)
    y4 = models.CharField(max_length=200, default=0)
    j4 = models.CharField(max_length=200, default=0)
    n4 = models.CharField(max_length=200, default=0)
    t5 = models.CharField(max_length=200, default=0)
    y5 = models.CharField(max_length=200, default=0)
    j5 = models.CharField(max_length=200, default=0)
    n5 = models.CharField(max_length=200, default=0)
    t6 = models.CharField(max_length=200, default=0)
    y6 = models.CharField(max_length=200, default=0)
    j6 = models.CharField(max_length=200, default=0)
    n6 = models.CharField(max_length=200, default=0)
    t7 = models.CharField(max_length=200, default=0)
    y7 = models.CharField(max_length=200, default=0)
    j7 = models.CharField(max_length=200, default=0)
    n7 = models.CharField(max_length=200, default=0)
    t8 = models.CharField(max_length=200, default=0)
    y8 = models.CharField(max_length=200, default=0)
    j8 = models.CharField(max_length=200, default=0)
    n8 = models.CharField(max_length=200, default=0)
    t9 = models.CharField(max_length=200, default=0)
    y9 = models.CharField(max_length=200, default=0)
    j9 = models.CharField(max_length=200, default=0)
    n9 = models.CharField(max_length=200, default=0)
    t10 = models.CharField(max_length=200, default=0)
    y10 = models.CharField(max_length=200, default=0)
    j10 = models.CharField(max_length=200, default=0)
    n10 = models.CharField(max_length=200, default=0)
    t11 = models.CharField(max_length=200, default=0)
    y11 = models.CharField(max_length=200, default=0)
    j11 = models.CharField(max_length=200, default=0)
    n11 = models.CharField(max_length=200, default=0)
    t12 = models.CharField(max_length=200, default=0)
    y12 = models.CharField(max_length=200, default=0)
    j12 = models.CharField(max_length=200, default=0)
    n12 = models.CharField(max_length=200, default=0)
    t13 = models.CharField(max_length=200, default=0)
    y13 = models.CharField(max_length=200, default=0)
    j13 = models.CharField(max_length=200, default=0)
    n13 = models.CharField(max_length=200, default=0)
    t14 = models.CharField(max_length=200, default=0)
    y14 = models.CharField(max_length=200, default=0)
    j14 = models.CharField(max_length=200, default=0)
    n14 = models.CharField(max_length=200, default=0)
    t15 = models.CharField(max_length=200, default=0)
    y15 = models.CharField(max_length=200, default=0)
    j15 = models.CharField(max_length=200, default=0)
    n15 = models.CharField(max_length=200, default=0)

    def __str__(self):
        return str(self.user)

class seminar(models.Model):                                                        #models.CharField(max_length=200, default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    w1=models.CharField(max_length=200, default=0)                                  #workshop
    t1=models.CharField(max_length=200, default=0)                                  #title
    y1=models.CharField(max_length=200, default=0)                                  #year
    i1=models.CharField(max_length=200, default=0)                                  #institute
    n1=models.CharField(max_length=200, default=0)                                  #international/national
    w2 = models.CharField(max_length=200, default=0)
    t2 = models.CharField(max_length=200, default=0)
    y2 = models.CharField(max_length=200, default=0)
    i2 = models.CharField(max_length=200, default=0)
    n2 = models.CharField(max_length=200, default=0)
    w3 = models.CharField(max_length=200, default=0)
    t3 = models.CharField(max_length=200, default=0)
    y3 = models.CharField(max_length=200, default=0)
    i3 = models.CharField(max_length=200, default=0)
    n3 = models.CharField(max_length=200, default=0)
    w4 = models.CharField(max_length=200, default=0)
    t4 = models.CharField(max_length=200, default=0)
    y4 = models.CharField(max_length=200, default=0)
    i4 = models.CharField(max_length=200, default=0)
    n4 = models.CharField(max_length=200, default=0)
    w5 = models.CharField(max_length=200, default=0)
    t5 = models.CharField(max_length=200, default=0)
    y5 = models.CharField(max_length=200, default=0)
    i5 = models.CharField(max_length=200, default=0)
    n5 = models.CharField(max_length=200, default=0)
    w6 = models.CharField(max_length=200, default=0)
    t6 = models.CharField(max_length=200, default=0)
    y6 = models.CharField(max_length=200, default=0)
    i6 = models.CharField(max_length=200, default=0)
    n6 = models.CharField(max_length=200, default=0)
    w7 = models.CharField(max_length=200, default=0)
    t7 = models.CharField(max_length=200, default=0)
    y7 = models.CharField(max_length=200, default=0)
    i7 = models.CharField(max_length=200, default=0)
    n7 = models.CharField(max_length=200, default=0)
    w8 = models.CharField(max_length=200, default=0)
    t8 = models.CharField(max_length=200, default=0)
    y8 = models.CharField(max_length=200, default=0)
    i8 = models.CharField(max_length=200, default=0)
    n8 = models.CharField(max_length=200, default=0)
    w9 = models.CharField(max_length=200, default=0)
    t9 = models.CharField(max_length=200, default=0)
    y9 = models.CharField(max_length=200, default=0)
    i9 = models.CharField(max_length=200, default=0)
    n9 = models.CharField(max_length=200, default=0)
    w10 = models.CharField(max_length=200, default=0)
    t10 = models.CharField(max_length=200, default=0)
    y10 = models.CharField(max_length=200, default=0)
    i10 = models.CharField(max_length=200, default=0)
    n10 = models.CharField(max_length=200, default=0)
    w11 = models.CharField(max_length=200, default=0)
    t11 = models.CharField(max_length=200, default=0)
    y11 = models.CharField(max_length=200, default=0)
    i11 = models.CharField(max_length=200, default=0)
    n11 = models.CharField(max_length=200, default=0)
    w12 = models.CharField(max_length=200, default=0)
    t12 = models.CharField(max_length=200, default=0)
    y12 = models.CharField(max_length=200, default=0)
    i12 = models.CharField(max_length=200, default=0)
    n12 = models.CharField(max_length=200, default=0)
    w13 = models.CharField(max_length=200, default=0)
    t13 = models.CharField(max_length=200, default=0)
    y13 = models.CharField(max_length=200, default=0)
    i13 = models.CharField(max_length=200, default=0)
    n13 = models.CharField(max_length=200, default=0)
    w14 = models.CharField(max_length=200, default=0)
    t14 = models.CharField(max_length=200, default=0)
    y14 = models.CharField(max_length=200, default=0)
    i14 = models.CharField(max_length=200, default=0)
    n14 = models.CharField(max_length=200, default=0)
    w15 = models.CharField(max_length=200, default=0)
    t15 = models.CharField(max_length=200, default=0)
    y15 = models.CharField(max_length=200, default=0)
    i15 = models.CharField(max_length=200, default=0)
    n15 = models.CharField(max_length=200, default=0)

    def __str__(self):
        return str(self.user)

class student(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    roll_no = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    ph_no = models.CharField(max_length=200, null=True, blank=True)
    dob = models.CharField(max_length=200, null=True, blank=True)
    gender = models.CharField(max_length=200, null=True, blank=True)
    father_name = models.CharField(max_length=200, null=True, blank=True)
    father_no = models.CharField(max_length=200, null=True, blank=True)
    religion = models.CharField(max_length=200, null=True, blank=True)
    caste = models.CharField(max_length=200, null=True, blank=True)
    status = models.CharField(max_length=200, null=True, blank=True)
    mtongue = models.CharField(max_length=200, null=True, blank=True)
    bgroup = models.CharField(max_length=200, null=True, blank=True)
    nation = models.CharField(max_length=200, null=True, blank=True)
    hostel = models.CharField(max_length=200, null=True, blank=True)
    morg = models.CharField(max_length=200, null=True, blank=True)
    sports = models.CharField(max_length=200, null=True, blank=True)
    lmark = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return str(self.name)


class sem1(models.Model):
    sid = models.OneToOneField(student, on_delete=models.CASCADE, blank=True, null=True)

    SC1 = models.CharField(max_length=100, default='--')
    SN1 = models.CharField(max_length=100, default='--')
    T11 = models.CharField(max_length=100, default='--')
    Q11 = models.CharField(max_length=100, default='--')
    A11 = models.CharField(max_length=100, default='--')
    T21 = models.CharField(max_length=100, default='--')
    Q21 = models.CharField(max_length=100, default='--')
    A21 = models.CharField(max_length=100, default='--')
    TO1 = models.CharField(max_length=100, default='--')
    E1 = models.CharField(max_length=100, default='--')

    SC2 = models.CharField(max_length=100, default='--')
    SN2 = models.CharField(max_length=100, default='--')
    T12 = models.CharField(max_length=100, default='--')
    Q12 = models.CharField(max_length=100, default='--')
    A12 = models.CharField(max_length=100, default='--')
    T22 = models.CharField(max_length=100, default='--')
    Q22 = models.CharField(max_length=100, default='--')
    A22 = models.CharField(max_length=100, default='--')
    TO2 = models.CharField(max_length=100, default='--')
    E2 = models.CharField(max_length=100, default='--')

    SC3 = models.CharField(max_length=100, default='--')
    SN3 = models.CharField(max_length=100, default='--')
    T13 = models.CharField(max_length=100, default='--')
    Q13 = models.CharField(max_length=100, default='--')
    A13 = models.CharField(max_length=100, default='--')
    T23 = models.CharField(max_length=100, default='--')
    Q23 = models.CharField(max_length=100, default='--')
    A23 = models.CharField(max_length=100, default='--')
    TO3 = models.CharField(max_length=100, default='--')
    E3 = models.CharField(max_length=100, default='--')

    SC4 = models.CharField(max_length=100, default='--')
    SN4 = models.CharField(max_length=100, default='--')
    T14 = models.CharField(max_length=100, default='--')
    Q14 = models.CharField(max_length=100, default='--')
    A14 = models.CharField(max_length=100, default='--')
    T24 = models.CharField(max_length=100, default='--')
    Q24 = models.CharField(max_length=100, default='--')
    A24 = models.CharField(max_length=100, default='--')
    TO4 = models.CharField(max_length=100, default='--')
    E4 = models.CharField(max_length=100, default='--')

    SC5 = models.CharField(max_length=100, default='--')
    SN5 = models.CharField(max_length=100, default='--')
    T15 = models.CharField(max_length=100, default='--')
    Q15 = models.CharField(max_length=100, default='--')
    A15 = models.CharField(max_length=100, default='--')
    T25 = models.CharField(max_length=100, default='--')
    Q25 = models.CharField(max_length=100, default='--')
    A25 = models.CharField(max_length=100, default='--')
    TO5 = models.CharField(max_length=100, default='--')
    E5 = models.CharField(max_length=100, default='--')

    SC6 = models.CharField(max_length=100, default='--')
    SN6 = models.CharField(max_length=100, default='--')
    T16 = models.CharField(max_length=100, default='--')
    Q16 = models.CharField(max_length=100, default='--')
    A16 = models.CharField(max_length=100, default='--')
    T26 = models.CharField(max_length=100, default='--')
    Q26 = models.CharField(max_length=100, default='--')
    A26 = models.CharField(max_length=100, default='--')
    TO6 = models.CharField(max_length=100, default='--')
    E6 = models.CharField(max_length=100, default='--')

    SC7 = models.CharField(max_length=100, default='--')
    SN7 = models.CharField(max_length=100, default='--')
    T17 = models.CharField(max_length=100, default='--')
    Q17 = models.CharField(max_length=100, default='--')
    A17 = models.CharField(max_length=100, default='--')
    T27 = models.CharField(max_length=100, default='--')
    Q27 = models.CharField(max_length=100, default='--')
    A27 = models.CharField(max_length=100, default='--')
    TO7 = models.CharField(max_length=100, default='--')
    E7 = models.CharField(max_length=100, default='--')

    def __str__(self):
        return str(self.sid)


class sem2(models.Model):
    sid = models.OneToOneField(student, on_delete=models.CASCADE, blank=True, null=True)

    SC1 = models.CharField(max_length=100, default='--')
    SN1 = models.CharField(max_length=100, default='--')
    T11 = models.CharField(max_length=100, default='--')
    Q11 = models.CharField(max_length=100, default='--')
    A11 = models.CharField(max_length=100, default='--')
    T21 = models.CharField(max_length=100, default='--')
    Q21 = models.CharField(max_length=100, default='--')
    A21 = models.CharField(max_length=100, default='--')
    TO1 = models.CharField(max_length=100, default='--')
    E1 = models.CharField(max_length=100, default='--')

    SC2 = models.CharField(max_length=100, default='--')
    SN2 = models.CharField(max_length=100, default='--')
    T12 = models.CharField(max_length=100, default='--')
    Q12 = models.CharField(max_length=100, default='--')
    A12 = models.CharField(max_length=100, default='--')
    T22 = models.CharField(max_length=100, default='--')
    Q22 = models.CharField(max_length=100, default='--')
    A22 = models.CharField(max_length=100, default='--')
    TO2 = models.CharField(max_length=100, default='--')
    E2 = models.CharField(max_length=100, default='--')

    SC3 = models.CharField(max_length=100, default='--')
    SN3 = models.CharField(max_length=100, default='--')
    T13 = models.CharField(max_length=100, default='--')
    Q13 = models.CharField(max_length=100, default='--')
    A13 = models.CharField(max_length=100, default='--')
    T23 = models.CharField(max_length=100, default='--')
    Q23 = models.CharField(max_length=100, default='--')
    A23 = models.CharField(max_length=100, default='--')
    TO3 = models.CharField(max_length=100, default='--')
    E3 = models.CharField(max_length=100, default='--')

    SC4 = models.CharField(max_length=100, default='--')
    SN4 = models.CharField(max_length=100, default='--')
    T14 = models.CharField(max_length=100, default='--')
    Q14 = models.CharField(max_length=100, default='--')
    A14 = models.CharField(max_length=100, default='--')
    T24 = models.CharField(max_length=100, default='--')
    Q24 = models.CharField(max_length=100, default='--')
    A24 = models.CharField(max_length=100, default='--')
    TO4 = models.CharField(max_length=100, default='--')
    E4 = models.CharField(max_length=100, default='--')

    SC5 = models.CharField(max_length=100, default='--')
    SN5 = models.CharField(max_length=100, default='--')
    T15 = models.CharField(max_length=100, default='--')
    Q15 = models.CharField(max_length=100, default='--')
    A15 = models.CharField(max_length=100, default='--')
    T25 = models.CharField(max_length=100, default='--')
    Q25 = models.CharField(max_length=100, default='--')
    A25 = models.CharField(max_length=100, default='--')
    TO5 = models.CharField(max_length=100, default='--')
    E5 = models.CharField(max_length=100, default='--')

    SC6 = models.CharField(max_length=100, default='--')
    SN6 = models.CharField(max_length=100, default='--')
    T16 = models.CharField(max_length=100, default='--')
    Q16 = models.CharField(max_length=100, default='--')
    A16 = models.CharField(max_length=100, default='--')
    T26 = models.CharField(max_length=100, default='--')
    Q26 = models.CharField(max_length=100, default='--')
    A26 = models.CharField(max_length=100, default='--')
    TO6 = models.CharField(max_length=100, default='--')
    E6 = models.CharField(max_length=100, default='--')

    SC7 = models.CharField(max_length=100, default='--')
    SN7 = models.CharField(max_length=100, default='--')
    T17 = models.CharField(max_length=100, default='--')
    Q17 = models.CharField(max_length=100, default='--')
    A17 = models.CharField(max_length=100, default='--')
    T27 = models.CharField(max_length=100, default='--')
    Q27 = models.CharField(max_length=100, default='--')
    A27 = models.CharField(max_length=100, default='--')
    TO7 = models.CharField(max_length=100, default='--')
    E7 = models.CharField(max_length=100, default='--')

    def __str__(self):
        return str(self.sid)


class sem3(models.Model):
    sid = models.OneToOneField(student, on_delete=models.CASCADE, blank=True, null=True)

    SC1 = models.CharField(max_length=100, default='--')
    SN1 = models.CharField(max_length=100, default='--')
    T11 = models.CharField(max_length=100, default='--')
    Q11 = models.CharField(max_length=100, default='--')
    A11 = models.CharField(max_length=100, default='--')
    T21 = models.CharField(max_length=100, default='--')
    Q21 = models.CharField(max_length=100, default='--')
    A21 = models.CharField(max_length=100, default='--')
    TO1 = models.CharField(max_length=100, default='--')
    E1 = models.CharField(max_length=100, default='--')

    SC2 = models.CharField(max_length=100, default='--')
    SN2 = models.CharField(max_length=100, default='--')
    T12 = models.CharField(max_length=100, default='--')
    Q12 = models.CharField(max_length=100, default='--')
    A12 = models.CharField(max_length=100, default='--')
    T22 = models.CharField(max_length=100, default='--')
    Q22 = models.CharField(max_length=100, default='--')
    A22 = models.CharField(max_length=100, default='--')
    TO2 = models.CharField(max_length=100, default='--')
    E2 = models.CharField(max_length=100, default='--')

    SC3 = models.CharField(max_length=100, default='--')
    SN3 = models.CharField(max_length=100, default='--')
    T13 = models.CharField(max_length=100, default='--')
    Q13 = models.CharField(max_length=100, default='--')
    A13 = models.CharField(max_length=100, default='--')
    T23 = models.CharField(max_length=100, default='--')
    Q23 = models.CharField(max_length=100, default='--')
    A23 = models.CharField(max_length=100, default='--')
    TO3 = models.CharField(max_length=100, default='--')
    E3 = models.CharField(max_length=100, default='--')

    SC4 = models.CharField(max_length=100, default='--')
    SN4 = models.CharField(max_length=100, default='--')
    T14 = models.CharField(max_length=100, default='--')
    Q14 = models.CharField(max_length=100, default='--')
    A14 = models.CharField(max_length=100, default='--')
    T24 = models.CharField(max_length=100, default='--')
    Q24 = models.CharField(max_length=100, default='--')
    A24 = models.CharField(max_length=100, default='--')
    TO4 = models.CharField(max_length=100, default='--')
    E4 = models.CharField(max_length=100, default='--')

    SC5 = models.CharField(max_length=100, default='--')
    SN5 = models.CharField(max_length=100, default='--')
    T15 = models.CharField(max_length=100, default='--')
    Q15 = models.CharField(max_length=100, default='--')
    A15 = models.CharField(max_length=100, default='--')
    T25 = models.CharField(max_length=100, default='--')
    Q25 = models.CharField(max_length=100, default='--')
    A25 = models.CharField(max_length=100, default='--')
    TO5 = models.CharField(max_length=100, default='--')
    E5 = models.CharField(max_length=100, default='--')

    SC6 = models.CharField(max_length=100, default='--')
    SN6 = models.CharField(max_length=100, default='--')
    T16 = models.CharField(max_length=100, default='--')
    Q16 = models.CharField(max_length=100, default='--')
    A16 = models.CharField(max_length=100, default='--')
    T26 = models.CharField(max_length=100, default='--')
    Q26 = models.CharField(max_length=100, default='--')
    A26 = models.CharField(max_length=100, default='--')
    TO6 = models.CharField(max_length=100, default='--')
    E6 = models.CharField(max_length=100, default='--')

    SC7 = models.CharField(max_length=100, default='--')
    SN7 = models.CharField(max_length=100, default='--')
    T17 = models.CharField(max_length=100, default='--')
    Q17 = models.CharField(max_length=100, default='--')
    A17 = models.CharField(max_length=100, default='--')
    T27 = models.CharField(max_length=100, default='--')
    Q27 = models.CharField(max_length=100, default='--')
    A27 = models.CharField(max_length=100, default='--')
    TO7 = models.CharField(max_length=100, default='--')
    E7 = models.CharField(max_length=100, default='--')

    def __str__(self):
        return str(self.sid)


class sem4(models.Model):
    sid = models.OneToOneField(student, on_delete=models.CASCADE, blank=True, null=True)

    SC1 = models.CharField(max_length=100, default='--')
    SN1 = models.CharField(max_length=100, default='--')
    T11 = models.CharField(max_length=100, default='--')
    Q11 = models.CharField(max_length=100, default='--')
    A11 = models.CharField(max_length=100, default='--')
    T21 = models.CharField(max_length=100, default='--')
    Q21 = models.CharField(max_length=100, default='--')
    A21 = models.CharField(max_length=100, default='--')
    TO1 = models.CharField(max_length=100, default='--')
    E1 = models.CharField(max_length=100, default='--')

    SC2 = models.CharField(max_length=100, default='--')
    SN2 = models.CharField(max_length=100, default='--')
    T12 = models.CharField(max_length=100, default='--')
    Q12 = models.CharField(max_length=100, default='--')
    A12 = models.CharField(max_length=100, default='--')
    T22 = models.CharField(max_length=100, default='--')
    Q22 = models.CharField(max_length=100, default='--')
    A22 = models.CharField(max_length=100, default='--')
    TO2 = models.CharField(max_length=100, default='--')
    E2 = models.CharField(max_length=100, default='--')

    SC3 = models.CharField(max_length=100, default='--')
    SN3 = models.CharField(max_length=100, default='--')
    T13 = models.CharField(max_length=100, default='--')
    Q13 = models.CharField(max_length=100, default='--')
    A13 = models.CharField(max_length=100, default='--')
    T23 = models.CharField(max_length=100, default='--')
    Q23 = models.CharField(max_length=100, default='--')
    A23 = models.CharField(max_length=100, default='--')
    TO3 = models.CharField(max_length=100, default='--')
    E3 = models.CharField(max_length=100, default='--')

    SC4 = models.CharField(max_length=100, default='--')
    SN4 = models.CharField(max_length=100, default='--')
    T14 = models.CharField(max_length=100, default='--')
    Q14 = models.CharField(max_length=100, default='--')
    A14 = models.CharField(max_length=100, default='--')
    T24 = models.CharField(max_length=100, default='--')
    Q24 = models.CharField(max_length=100, default='--')
    A24 = models.CharField(max_length=100, default='--')
    TO4 = models.CharField(max_length=100, default='--')
    E4 = models.CharField(max_length=100, default='--')

    SC5 = models.CharField(max_length=100, default='--')
    SN5 = models.CharField(max_length=100, default='--')
    T15 = models.CharField(max_length=100, default='--')
    Q15 = models.CharField(max_length=100, default='--')
    A15 = models.CharField(max_length=100, default='--')
    T25 = models.CharField(max_length=100, default='--')
    Q25 = models.CharField(max_length=100, default='--')
    A25 = models.CharField(max_length=100, default='--')
    TO5 = models.CharField(max_length=100, default='--')
    E5 = models.CharField(max_length=100, default='--')

    SC6 = models.CharField(max_length=100, default='--')
    SN6 = models.CharField(max_length=100, default='--')
    T16 = models.CharField(max_length=100, default='--')
    Q16 = models.CharField(max_length=100, default='--')
    A16 = models.CharField(max_length=100, default='--')
    T26 = models.CharField(max_length=100, default='--')
    Q26 = models.CharField(max_length=100, default='--')
    A26 = models.CharField(max_length=100, default='--')
    TO6 = models.CharField(max_length=100, default='--')
    E6 = models.CharField(max_length=100, default='--')

    SC7 = models.CharField(max_length=100, default='--')
    SN7 = models.CharField(max_length=100, default='--')
    T17 = models.CharField(max_length=100, default='--')
    Q17 = models.CharField(max_length=100, default='--')
    A17 = models.CharField(max_length=100, default='--')
    T27 = models.CharField(max_length=100, default='--')
    Q27 = models.CharField(max_length=100, default='--')
    A27 = models.CharField(max_length=100, default='--')
    TO7 = models.CharField(max_length=100, default='--')
    E7 = models.CharField(max_length=100, default='--')

    def __str__(self):
        return str(self.sid)


class sem5(models.Model):
    sid = models.OneToOneField(student, on_delete=models.CASCADE, blank=True, null=True)

    SC1 = models.CharField(max_length=100, default='--')
    SN1 = models.CharField(max_length=100, default='--')
    T11 = models.CharField(max_length=100, default='--')
    Q11 = models.CharField(max_length=100, default='--')
    A11 = models.CharField(max_length=100, default='--')
    T21 = models.CharField(max_length=100, default='--')
    Q21 = models.CharField(max_length=100, default='--')
    A21 = models.CharField(max_length=100, default='--')
    TO1 = models.CharField(max_length=100, default='--')
    E1 = models.CharField(max_length=100, default='--')

    SC2 = models.CharField(max_length=100, default='--')
    SN2 = models.CharField(max_length=100, default='--')
    T12 = models.CharField(max_length=100, default='--')
    Q12 = models.CharField(max_length=100, default='--')
    A12 = models.CharField(max_length=100, default='--')
    T22 = models.CharField(max_length=100, default='--')
    Q22 = models.CharField(max_length=100, default='--')
    A22 = models.CharField(max_length=100, default='--')
    TO2 = models.CharField(max_length=100, default='--')
    E2 = models.CharField(max_length=100, default='--')

    SC3 = models.CharField(max_length=100, default='--')
    SN3 = models.CharField(max_length=100, default='--')
    T13 = models.CharField(max_length=100, default='--')
    Q13 = models.CharField(max_length=100, default='--')
    A13 = models.CharField(max_length=100, default='--')
    T23 = models.CharField(max_length=100, default='--')
    Q23 = models.CharField(max_length=100, default='--')
    A23 = models.CharField(max_length=100, default='--')
    TO3 = models.CharField(max_length=100, default='--')
    E3 = models.CharField(max_length=100, default='--')

    SC4 = models.CharField(max_length=100, default='--')
    SN4 = models.CharField(max_length=100, default='--')
    T14 = models.CharField(max_length=100, default='--')
    Q14 = models.CharField(max_length=100, default='--')
    A14 = models.CharField(max_length=100, default='--')
    T24 = models.CharField(max_length=100, default='--')
    Q24 = models.CharField(max_length=100, default='--')
    A24 = models.CharField(max_length=100, default='--')
    TO4 = models.CharField(max_length=100, default='--')
    E4 = models.CharField(max_length=100, default='--')

    SC5 = models.CharField(max_length=100, default='--')
    SN5 = models.CharField(max_length=100, default='--')
    T15 = models.CharField(max_length=100, default='--')
    Q15 = models.CharField(max_length=100, default='--')
    A15 = models.CharField(max_length=100, default='--')
    T25 = models.CharField(max_length=100, default='--')
    Q25 = models.CharField(max_length=100, default='--')
    A25 = models.CharField(max_length=100, default='--')
    TO5 = models.CharField(max_length=100, default='--')
    E5 = models.CharField(max_length=100, default='--')

    SC6 = models.CharField(max_length=100, default='--')
    SN6 = models.CharField(max_length=100, default='--')
    T16 = models.CharField(max_length=100, default='--')
    Q16 = models.CharField(max_length=100, default='--')
    A16 = models.CharField(max_length=100, default='--')
    T26 = models.CharField(max_length=100, default='--')
    Q26 = models.CharField(max_length=100, default='--')
    A26 = models.CharField(max_length=100, default='--')
    TO6 = models.CharField(max_length=100, default='--')
    E6 = models.CharField(max_length=100, default='--')

    SC7 = models.CharField(max_length=100, default='--')
    SN7 = models.CharField(max_length=100, default='--')
    T17 = models.CharField(max_length=100, default='--')
    Q17 = models.CharField(max_length=100, default='--')
    A17 = models.CharField(max_length=100, default='--')
    T27 = models.CharField(max_length=100, default='--')
    Q27 = models.CharField(max_length=100, default='--')
    A27 = models.CharField(max_length=100, default='--')
    TO7 = models.CharField(max_length=100, default='--')
    E7 = models.CharField(max_length=100, default='--')

    def __str__(self):
        return str(self.sid)

class event(models.Model):
    date=models.DateField()
    title=models.CharField(max_length=100)
    description=models.CharField(max_length=1000,null=True)
    host=models.CharField(max_length=100,null=True)
    level=models.CharField(max_length=100,null=True)


