# Generated by Django 2.1.7 on 2021-04-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIS', '0004_ap_article_oe_seminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='spint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
